package com.inspireme.app.ui.theme;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Random;

public class QuoteManager {

    private static final Map<String, List<Quote>> categorizedQuotes = new HashMap<>();
    private static final Random random = new Random();

    static {
        initializeQuotes();
    }

    private static void initializeQuotes() {
        // MOTIVATIONAL QUOTES (80+ quotes)
        List<Quote> motivational = new ArrayList<>();
        motivational.add(new Quote("The only way to do great work is to love what you do.", "Steve Jobs"));
        motivational.add(new Quote("Innovation distinguishes between a leader and a follower.", "Steve Jobs"));
        motivational.add(new Quote("The way to get started is to quit talking and begin doing.", "Walt Disney"));
        motivational.add(new Quote("Don't let yesterday take up too much of today.", "Will Rogers"));
        motivational.add(new Quote("Believe you can and you're halfway there.", "Theodore Roosevelt"));
        motivational.add(new Quote("The only impossible journey is the one you never begin.", "Tony Robbins"));
        motivational.add(new Quote("Never let the fear of striking out keep you from playing the game.", "Babe Ruth"));
        motivational.add(new Quote("All our dreams can come true if we have the courage to pursue them.", "Walt Disney"));
        motivational.add(new Quote("Good things happen to those who work hard.", "Unknown"));
        motivational.add(new Quote("Dreams don't work unless you take action.", "Unknown"));
        motivational.add(new Quote("Push yourself because no one else is going to do it for you.", "Unknown"));
        motivational.add(new Quote("Great things never come from comfort zones.", "Unknown"));
        motivational.add(new Quote("Don't stop when you're tired. Stop when you're done.", "Unknown"));
        motivational.add(new Quote("Wake up with determination. Go to bed with satisfaction.", "Unknown"));
        motivational.add(new Quote("Do something today that your future self will thank you for.", "Sean Patrick Flanery"));
        motivational.add(new Quote("The difference between ordinary and extraordinary is that little extra.", "Jimmy Johnson"));
        motivational.add(new Quote("Success is not final, failure is not fatal, it is the courage to continue that counts.", "Winston Churchill"));
        motivational.add(new Quote("Don't watch the clock; do what it does. Keep going.", "Sam Levenson"));
        motivational.add(new Quote("The harder you work for something, the greater you'll feel when you achieve it.", "Unknown"));
        motivational.add(new Quote("Don't limit your challenges, challenge your limits.", "Unknown"));
        motivational.add(new Quote("A goal is a dream with a deadline.", "Napoleon Hill"));
        motivational.add(new Quote("You are never too old to set another goal or to dream a new dream.", "C.S. Lewis"));
        motivational.add(new Quote("What lies behind us and what lies before us are tiny matters compared to what lies within us.", "Ralph Waldo Emerson"));
        motivational.add(new Quote("The only person you are destined to become is the person you decide to be.", "Ralph Waldo Emerson"));
        motivational.add(new Quote("Your limitation—it's only your imagination.", "Unknown"));
        motivational.add(new Quote("Sometimes we're tested not to show our weaknesses, but to discover our strengths.", "Unknown"));
        motivational.add(new Quote("The key to success is to focus on goals, not obstacles.", "Unknown"));
        motivational.add(new Quote("Dream it. Believe it. Build it.", "Unknown"));
        motivational.add(new Quote("Your potential is endless.", "Unknown"));
        motivational.add(new Quote("Be yourself; everyone else is already taken.", "Oscar Wilde"));
        motivational.add(new Quote("Turn your wounds into wisdom.", "Oprah Winfrey"));
        motivational.add(new Quote("Believe in yourself and all that you are.", "Christian D. Larson"));
        motivational.add(new Quote("The future belongs to those who believe in the beauty of their dreams.", "Eleanor Roosevelt"));
        motivational.add(new Quote("It is during our darkest moments that we must focus to see the light.", "Aristotle"));
        motivational.add(new Quote("In the middle of difficulty lies opportunity.", "Albert Einstein"));
        motivational.add(new Quote("Champions keep playing until they get it right.", "Billie Jean King"));
        motivational.add(new Quote("You miss 100% of the shots you don't take.", "Wayne Gretzky"));
        motivational.add(new Quote("Whether you think you can or you think you can't, you're right.", "Henry Ford"));
        motivational.add(new Quote("The only way to achieve the impossible is to believe it is possible.", "Charles Kingsleigh"));
        motivational.add(new Quote("Strength doesn't come from what you can do. It comes from overcoming what you thought you couldn't.", "Rikki Rogers"));
        motivational.add(new Quote("Don't be afraid to give up the good to go for the great.", "John D. Rockefeller"));
        motivational.add(new Quote("The best time to plant a tree was 20 years ago. The second best time is now.", "Chinese Proverb"));
        motivational.add(new Quote("A year from now you may wish you had started today.", "Karen Lamb"));
        motivational.add(new Quote("You are braver than you believe, stronger than you seem, and smarter than you think.", "A.A. Milne"));
        motivational.add(new Quote("The greatest glory in living lies not in never falling, but in rising every time we fall.", "Nelson Mandela"));
        motivational.add(new Quote("Life is what happens to you while you're busy making other plans.", "John Lennon"));
        motivational.add(new Quote("The future belongs to those who prepare for it today.", "Malcolm X"));
        motivational.add(new Quote("Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.", "Roy T. Bennett"));
        motivational.add(new Quote("Difficult roads often lead to beautiful destinations.", "Zig Ziglar"));
        motivational.add(new Quote("Everything you need is inside you.", "Unknown"));
        motivational.add(new Quote("Be the change you wish to see in the world.", "Mahatma Gandhi"));
        motivational.add(new Quote("Life begins at the end of your comfort zone.", "Neale Donald Walsch"));
        motivational.add(new Quote("If you want to achieve greatness stop asking for permission.", "Unknown"));
        motivational.add(new Quote("Things work out best for those who make the best of how things work out.", "John Wooden"));
        motivational.add(new Quote("To live a creative life, we must lose our fear of being wrong.", "Unknown"));
        motivational.add(new Quote("If you are not willing to risk the usual you will have to settle for the ordinary.", "Jim Rohn"));
        motivational.add(new Quote("Trust because you are willing to accept the risk, not because it's safe or certain.", "Unknown"));
        motivational.add(new Quote("Take up one idea. Make that one idea your life—think of it, dream of it, live on that idea.", "Swami Vivekananda"));
        motivational.add(new Quote("All our dreams can come true if we have the courage to pursue them.", "Walt Disney"));
        motivational.add(new Quote("Good things happen to people who work hard.", "Unknown"));
        motivational.add(new Quote("Don't let what you cannot do interfere with what you can do.", "John Wooden"));
        motivational.add(new Quote("You can't go back and change the beginning, but you can start where you are and change the ending.", "C.S. Lewis"));
        motivational.add(new Quote("Believe you can and you're halfway there.", "Theodore Roosevelt"));
        motivational.add(new Quote("Act as if what you do makes a difference. It does.", "William James"));
        motivational.add(new Quote("Success is not how high you have climbed, but how you make a positive difference to the world.", "Roy T. Bennett"));
        motivational.add(new Quote("What we achieve inwardly will change outer reality.", "Plutarch"));
        motivational.add(new Quote("An unexamined life is not worth living.", "Socrates"));
        motivational.add(new Quote("Your true success in life begins only when you make the commitment to become excellent at what you do.", "Brian Tracy"));
        motivational.add(new Quote("Believe in yourself, take on your challenges, dig deep within yourself to conquer fears.", "Chantal Sutherland"));
        motivational.add(new Quote("Never give up on a dream just because of the time it will take to accomplish it.", "Earl Nightingale"));
        motivational.add(new Quote("The only person you are destined to become is the person you decide to be.", "Ralph Waldo Emerson"));
        motivational.add(new Quote("Go confidently in the direction of your dreams. Live the life you have imagined.", "Henry David Thoreau"));
        motivational.add(new Quote("When one door of happiness closes, another opens.", "Helen Keller"));
        motivational.add(new Quote("Life is really simple, but we insist on making it complicated.", "Confucius"));
        motivational.add(new Quote("May you live all the days of your life.", "Jonathan Swift"));
        motivational.add(new Quote("Life is a succession of lessons which must be lived to be understood.", "Helen Keller"));
        motivational.add(new Quote("Your time is limited, so don't waste it living someone else's life.", "Steve Jobs"));
        motivational.add(new Quote("Growing up is losing some illusions, in order to acquire others.", "Virginia Woolf"));
        motivational.add(new Quote("The only impossible journey is the one you never begin.", "Tony Robbins"));
        motivational.add(new Quote("In this life we cannot do great things. We can only do small things with great love.", "Mother Teresa"));
        motivational.add(new Quote("If life were predictable it would cease to be life, and be without flavor.", "Eleanor Roosevelt"));
        motivational.add(new Quote("In order to write about life first you must live it.", "Ernest Hemingway"));
        motivational.add(new Quote("The big lesson in life, baby, is never be scared of anyone or anything.", "Frank Sinatra"));
        motivational.add(new Quote("Sing like nobody's listening, love like you've never been hurt, dance like nobody's watching, and live like it's heaven on earth.", "Susanna Clark"));

        // SUCCESS QUOTES (70+ quotes)
        List<Quote> success = new ArrayList<>();
        success.add(new Quote("Success is not final, failure is not fatal: it is the courage to continue that counts.", "Winston Churchill"));
        success.add(new Quote("You learn more from failure than from success.", "Unknown"));
        success.add(new Quote("Many of life's failures are people who did not realize how close they were to success when they gave up.", "Thomas A. Edison"));
        success.add(new Quote("Money and success don't change people; they merely amplify what is already there.", "Will Smith"));
        success.add(new Quote("Success is walking from failure to failure with no loss of enthusiasm.", "Winston Churchill"));
        success.add(new Quote("The road to success and the road to failure are almost exactly the same.", "Colin R. Davis"));
        success.add(new Quote("Success is not how high you have climbed, but how you make a positive difference to the world.", "Roy T. Bennett"));
        success.add(new Quote("Don't be afraid to give up the good to go for the great.", "John D. Rockefeller"));
        success.add(new Quote("The successful warrior is the average man with laser-like focus.", "Bruce Lee"));
        success.add(new Quote("Success is the sum of small efforts repeated day in and day out.", "Robert Collier"));
        success.add(new Quote("The way to get started is to quit talking and begin doing.", "Walt Disney"));
        success.add(new Quote("Innovation distinguishes between a leader and a follower.", "Steve Jobs"));
        success.add(new Quote("Your time is limited, so don't waste it living someone else's life.", "Steve Jobs"));
        success.add(new Quote("If you really look closely, most overnight successes took a long time.", "Steve Jobs"));
        success.add(new Quote("The only impossible journey is the one you never begin.", "Tony Robbins"));
        success.add(new Quote("Success is liking yourself, liking what you do, and liking how you do it.", "Maya Angelou"));
        success.add(new Quote("Try not to become a person of success, but rather try to become a person of value.", "Albert Einstein"));
        success.add(new Quote("It is better to fail in originality than to succeed in imitation.", "Herman Melville"));
        success.add(new Quote("The road to success is always under construction.", "Lily Tomlin"));
        success.add(new Quote("Success is not the key to happiness. Happiness is the key to success.", "Albert Schweitzer"));
        success.add(new Quote("Don't let the fear of losing be greater than the excitement of winning.", "Robert Kiyosaki"));
        success.add(new Quote("If you want to achieve excellence, you can get there today.", "Thomas J. Watson"));
        success.add(new Quote("Success is a lousy teacher. It seduces smart people into thinking they can't lose.", "Bill Gates"));
        success.add(new Quote("Successful people do what unsuccessful people are not willing to do.", "Jeff Olson"));
        success.add(new Quote("The difference between successful people and really successful people is that really successful people say no to almost everything.", "Warren Buffett"));
        success.add(new Quote("Success is going from failure to failure without losing your enthusiasm.", "Winston Churchill"));
        success.add(new Quote("The secret of success is to do the common thing uncommonly well.", "John D. Rockefeller Jr."));
        success.add(new Quote("I find that the harder I work, the more luck I seem to have.", "Thomas Jefferson"));
        success.add(new Quote("Don't aim for success if you want it; just do what you love and believe in.", "David Frost"));
        success.add(new Quote("Success is not in what you have, but who you are.", "Bo Bennett"));
        success.add(new Quote("Fall seven times and stand up eight.", "Japanese Proverb"));
        success.add(new Quote("Some people dream of success, while other people get up every morning and make it happen.", "Wayne Huizenga"));
        success.add(new Quote("There are no shortcuts to any place worth going.", "Beverly Sills"));
        success.add(new Quote("Success is the progressive realization of a worthy goal or ideal.", "Earl Nightingale"));
        success.add(new Quote("The pessimist sees difficulty in every opportunity. The optimist sees opportunity in every difficulty.", "Winston Churchill"));
        success.add(new Quote("Don't be distracted by criticism. Remember, the only taste of success some people get is to take a bite out of you.", "Zig Ziglar"));
        success.add(new Quote("Success is simple. Do what's right, the right way, at the right time.", "Arnold H. Glasow"));
        success.add(new Quote("If you genuinely want something, don't wait for it – teach yourself to be impatient.", "Gurbaksh Chahal"));
        success.add(new Quote("The starting point of all achievement is desire.", "Napoleon Hill"));
        success.add(new Quote("Success is where preparation and opportunity meet.", "Bobby Unser"));
        success.add(new Quote("Successful and unsuccessful people do not vary greatly in their abilities.", "John Maxwell"));
        success.add(new Quote("Success isn't just about what you accomplish in your life, it's about what you inspire others to do.", "Unknown"));
        success.add(new Quote("Nothing in the world can take the place of persistence.", "Calvin Coolidge"));
        success.add(new Quote("The successful man will profit from his mistakes and try again in a different way.", "Dale Carnegie"));
        success.add(new Quote("If you want to be successful, it's just this simple. Know what you are doing. Love what you are doing.", "Will Rogers"));
        success.add(new Quote("Success is a state of mind. If you want success, start thinking of yourself as a success.", "Joyce Brothers"));
        success.add(new Quote("Success is not a good teacher, failure makes you humble.", "Shah Rukh Khan"));
        success.add(new Quote("Success is achieved by developing our strengths, not by eliminating our weaknesses.", "Marilyn vos Savant"));
        success.add(new Quote("The successful person has the habit of doing the things failures don't like to do.", "Thomas Edison"));
        success.add(new Quote("Success comes to those who dare to begin.", "Eugene F. Ware"));
        success.add(new Quote("There are two types of people who will tell you that you cannot make a difference in this world: those who are afraid to try and those who are afraid you will succeed.", "Ray Goforth"));
        success.add(new Quote("Successful people are always looking for opportunities to help others.", "Brian Tracy"));
        success.add(new Quote("Before you can successfully make friends with others, first you have to become your own friend.", "Stephen Richards"));
        success.add(new Quote("Success is never final and failure never fatal. It's courage that counts.", "George F. Tilton"));
        success.add(new Quote("Success seems to be connected with action.", "Maya Angelou"));
        success.add(new Quote("Develop success from failures. Discouragement and failure are two of the surest stepping stones to success.", "Dale Carnegie"));
        success.add(new Quote("Success is not just a measure of how big you can dream, it is also a measure of how much you can do.", "Unknown"));
        success.add(new Quote("High expectations are the key to everything.", "Sam Walton"));
        success.add(new Quote("Success is not the absence of failure; it's the persistence through failure.", "Aisha Tyler"));
        success.add(new Quote("The ladder of success is best climbed by stepping on the rungs of opportunity.", "Ayn Rand"));
        success.add(new Quote("Success isn't given. It's earned in the gym, on the field, in every difficult decision.", "Unknown"));
        success.add(new Quote("The most successful people are those who are good at Plan B.", "James Yorke"));
        success.add(new Quote("Success is the ability to go from failure to failure without losing your enthusiasm.", "Winston Churchill"));
        success.add(new Quote("Success is not about the destination, it's about the journey.", "Zig Ziglar"));
        success.add(new Quote("I have not failed. I've just found 10,000 ways that won't work.", "Thomas A. Edison"));
        success.add(new Quote("Success is doing ordinary things extraordinarily well.", "Jim Rohn"));
        success.add(new Quote("The price of success is hard work, dedication to the job at hand.", "Vince Lombardi"));
        success.add(new Quote("Success is measured by how high you bounce when you hit bottom.", "George S. Patton"));

        // LIFE QUOTES (80+ quotes)
        List<Quote> life = new ArrayList<>();
        life.add(new Quote("Life is what happens to you while you're busy making other plans.", "John Lennon"));
        life.add(new Quote("Only a life lived for others is a life worthwhile.", "Albert Einstein"));
        life.add(new Quote("You only live once, but if you do it right, once is enough.", "Mae West"));
        life.add(new Quote("Your time is limited, so don't waste it living someone else's life.", "Steve Jobs"));
        life.add(new Quote("Not how long, but how well you have lived is the main thing.", "Seneca"));
        life.add(new Quote("Life is really simple, but we insist on making it complicated.", "Confucius"));
        life.add(new Quote("In the end, we will remember not the words of our enemies, but the silence of our friends.", "Martin Luther King Jr."));
        life.add(new Quote("Life is 10% what happens to you and 90% how you react to it.", "Charles R. Swindoll"));
        life.add(new Quote("The biggest adventure you can take is to live the life of your dreams.", "Oprah Winfrey"));
        life.add(new Quote("Life isn't about finding yourself. Life is about creating yourself.", "George Bernard Shaw"));
        life.add(new Quote("The purpose of our lives is to be happy.", "Dalai Lama"));
        life.add(new Quote("Life is a succession of lessons which must be lived to be understood.", "Helen Keller"));
        life.add(new Quote("In order to write about life first you must live it.", "Ernest Hemingway"));
        life.add(new Quote("Life is either a daring adventure or nothing at all.", "Helen Keller"));
        life.add(new Quote("The unexamined life is not worth living.", "Socrates"));
        life.add(new Quote("Turn your wounds into wisdom.", "Oprah Winfrey"));
        life.add(new Quote("The way I see it, if you want the rainbow, you gotta put up with the rain.", "Dolly Parton"));
        life.add(new Quote("Do all the good you can, for all the people you can, in all the ways you can, as long as you can.", "Hillary Clinton"));
        life.add(new Quote("Don't settle for what life gives you; make life better and build something.", "Ashton Kutcher"));
        life.add(new Quote("Everybody wants to be famous, but nobody wants to do the work.", "Kevin Hart"));
        life.add(new Quote("The time for action is now. It's never too late to do something.", "Antoine de Saint-Exupéry"));
        life.add(new Quote("Life is short, and it is here to be lived.", "Kate Winslet"));
        life.add(new Quote("Everything negative – pressure, challenges – is all an opportunity for me to rise.", "Kobe Bryant"));
        life.add(new Quote("I like criticism. It makes you strong.", "LeBron James"));
        life.add(new Quote("You never really learn much from hearing yourself speak.", "George Clooney"));
        life.add(new Quote("Life imposes things on you that you can't control, but you still have the choice of how you're going to live through this.", "Celine Dion"));
        life.add(new Quote("Life is never fair, and perhaps it is a good thing for most of us that it is not.", "Oscar Wilde"));
        life.add(new Quote("The only way to do great work is to love what you do.", "Steve Jobs"));
        life.add(new Quote("If you look at what you have in life, you'll always have more.", "Oprah Winfrey"));
        life.add(new Quote("Life itself is the most wonderful fairy tale.", "Hans Christian Andersen"));
        life.add(new Quote("Do not go where the path may lead, go instead where there is no path and leave a trail.", "Ralph Waldo Emerson"));
        life.add(new Quote("In three words I can sum up everything I've learned about life: it goes on.", "Robert Frost"));
        life.add(new Quote("Life is a dream for the wise, a game for the fool, a comedy for the rich, a tragedy for the poor.", "Sholom Aleichem"));
        life.add(new Quote("Life is really simple, but men insist on making it complicated.", "Confucius"));
        life.add(new Quote("May you live every day of your life.", "Jonathan Swift"));
        life.add(new Quote("Life is a long lesson in humility.", "James M. Barrie"));
        life.add(new Quote("In the end, it's not the years in your life that count. It's the life in your years.", "Abraham Lincoln"));
        life.add(new Quote("Life is what we make it, always has been, always will be.", "Grandma Moses"));
        life.add(new Quote("The good life is one inspired by love and guided by knowledge.", "Bertrand Russell"));
        life.add(new Quote("Life is a series of natural and spontaneous changes.", "Lao Tzu"));
        life.add(new Quote("Life loves to be taken by the lapel and told: I'm with you kid. Let's go.", "Maya Angelou"));
        life.add(new Quote("The secret to a happy life is to run out of cash and air at the same time.", "Bobby Layne"));
        life.add(new Quote("Life is 10% what happens to you and 90% how you respond to it.", "Lou Holtz"));
        life.add(new Quote("Life is not a problem to be solved, but a reality to be experienced.", "Soren Kierkegaard"));
        life.add(new Quote("You have within you right now, everything you need to deal with whatever the world can throw at you.", "Brian Tracy"));
        life.add(new Quote("Believe that life is worth living and your belief will help create the fact.", "William James"));
        life.add(new Quote("Life is 10% what you make it, and 90% how you take it.", "Irving Berlin"));
        life.add(new Quote("Life is a ticket to the greatest show on earth.", "Martin H. Fischer"));
        life.add(new Quote("We make a living by what we get, but we make a life by what we give.", "Winston Churchill"));
        life.add(new Quote("The secret of getting ahead is getting started.", "Mark Twain"));
        life.add(new Quote("Life shrinks or expands in proportion to one's courage.", "Anais Nin"));
        life.add(new Quote("If you want to live a happy life, tie it to a goal, not to people or things.", "Albert Einstein"));
        life.add(new Quote("Life is a mirror and will reflect back to the thinker what he thinks into it.", "Ernest Holmes"));
        life.add(new Quote("You get in life what you have the courage to ask for.", "Oprah Winfrey"));
        life.add(new Quote("Life is too important to be taken seriously.", "Oscar Wilde"));
        life.add(new Quote("Life is a daring adventure or nothing at all.", "Helen Keller"));
        life.add(new Quote("Many of life's failures are people who did not realize how close they were to success when they gave up.", "Thomas Edison"));
        life.add(new Quote("Don't cry because it's over, smile because it happened.", "Dr. Seuss"));
        life.add(new Quote("Be yourself; everyone else is already taken.", "Oscar Wilde"));
        life.add(new Quote("Two things are infinite: the universe and human stupidity; and I'm not sure about the universe.", "Albert Einstein"));
        life.add(new Quote("So many books, so little time.", "Frank Zappa"));
        life.add(new Quote("A room without books is like a body without a soul.", "Marcus Tullius Cicero"));
        life.add(new Quote("Be who you are and say what you feel, because those who mind don't matter, and those who matter don't mind.", "Bernard M. Baruch"));
        life.add(new Quote("You know you're in love when you can't fall asleep because reality is finally better than your dreams.", "Dr. Seuss"));
        life.add(new Quote("You only live once, but if you do it right, once is enough.", "Mae West"));
        life.add(new Quote("Be the change that you wish to see in the world.", "Mahatma Gandhi"));
        life.add(new Quote("In three words I can sum up everything I've learned about life: it goes on.", "Robert Frost"));
        life.add(new Quote("If you want to know what a man's like, take a good look at how he treats his inferiors, not his equals.", "J.K. Rowling"));
        life.add(new Quote("Don't walk in front of me… I may not follow Don't walk behind me… I may not lead Walk beside me… just be my friend.", "Albert Camus"));
        life.add(new Quote("No one can make you feel inferior without your consent.", "Eleanor Roosevelt"));
        life.add(new Quote("If you tell the truth, you don't have to remember anything.", "Mark Twain"));
        life.add(new Quote("Friendship is the only cement that will ever hold the world together.", "Woodrow Wilson"));
        life.add(new Quote("A friend is someone who knows all about you and still loves you.", "Elbert Hubbard"));
        life.add(new Quote("To live is the rarest thing in the world. Most people just exist.", "Oscar Wilde"));
        life.add(new Quote("It is not length of life, but depth of life.", "Ralph Waldo Emerson"));
        life.add(new Quote("Always forgive your enemies; nothing annoys them so much.", "Oscar Wilde"));
        life.add(new Quote("Live as if you were to die tomorrow. Learn as if you were to live forever.", "Mahatma Gandhi"));
        life.add(new Quote("We are all in the gutter, but some of us are looking at the stars.", "Oscar Wilde"));
        life.add(new Quote("It is during our darkest moments that we must focus to see the light.", "Aristotle"));
        life.add(new Quote("Yesterday is history, tomorrow is a mystery, today is a gift of God, which is why we call it the present.", "Bill Keane"));

        // HAPPINESS QUOTES (60+ quotes)
        List<Quote> happiness = new ArrayList<>();
        happiness.add(new Quote("The purpose of our lives is to be happy.", "Dalai Lama"));
        happiness.add(new Quote("If you want to live a happy life, tie it to a goal, not to people or things.", "Albert Einstein"));
        happiness.add(new Quote("Happiness is not something ready made. It comes from your own actions.", "Dalai Lama"));
        happiness.add(new Quote("Happiness is when what you think, what you say, and what you do are in harmony.", "Mahatma Gandhi"));
        happiness.add(new Quote("Be yourself; everyone else is already taken.", "Oscar Wilde"));
        happiness.add(new Quote("Two things are infinite: the universe and human stupidity; and I'm not sure about the universe.", "Albert Einstein"));
        happiness.add(new Quote("Be the change that you wish to see in the world.", "Mahatma Gandhi"));
        happiness.add(new Quote("The best way to cheer yourself is to try to cheer someone else up.", "Mark Twain"));
        happiness.add(new Quote("Happiness depends upon ourselves.", "Aristotle"));
        happiness.add(new Quote("The secret of happiness is not in doing what one likes, but in liking what one does.", "James M. Barrie"));
        happiness.add(new Quote("Happiness is a choice that requires effort at times.", "Aeschylus"));
        happiness.add(new Quote("The greatest happiness you can have is knowing that you do not necessarily require happiness.", "William Saroyan"));
        happiness.add(new Quote("Happiness is not by chance, but by choice.", "Jim Rohn"));
        happiness.add(new Quote("Very little is needed to make a happy life; it is all within yourself, in your way of thinking.", "Marcus Aurelius"));
        happiness.add(new Quote("The secret of being happy is accepting where you are in life and making the most out of every day.", "Unknown"));
        happiness.add(new Quote("Happiness is not the absence of problems, it's the ability to deal with them.", "Steve Maraboli"));
        happiness.add(new Quote("True happiness is to enjoy the present, without anxious dependence upon the future.", "Lucius Annaeus Seneca"));
        happiness.add(new Quote("Happiness is a direction, not a place.", "Sydney J. Harris"));
        happiness.add(new Quote("Count your age by friends, not years. Count your life by smiles, not tears.", "John Lennon"));
        happiness.add(new Quote("The most important thing is to enjoy your life—to be happy—it's all that matters.", "Audrey Hepburn"));
        happiness.add(new Quote("Happiness is when what you think, what you say, and what you do are in harmony.", "Mahatma Gandhi"));
        happiness.add(new Quote("Don't worry, be happy.", "Bobby McFerrin"));
        happiness.add(new Quote("The secret to happiness is freedom... And the secret to freedom is courage.", "Thucydides"));
        happiness.add(new Quote("Happiness can be found even in the darkest of times, if one only remembers to turn on the light.", "Albus Dumbledore"));
        happiness.add(new Quote("Happiness is not a goal; it is a by-product.", "Eleanor Roosevelt"));
        happiness.add(new Quote("The happiness of your life depends upon the quality of your thoughts.", "Marcus Aurelius"));
        happiness.add(new Quote("Be happy for this moment. This moment is your life.", "Omar Khayyam"));
        happiness.add(new Quote("Happiness is not something you postpone for the future; it is something you design for the present.", "Jim Rohn"));
        happiness.add(new Quote("The secret of happiness is to count your blessings while others are adding up their troubles.", "William Penn"));
        happiness.add(new Quote("Happiness is a warm puppy.", "Charles M. Schulz"));
        happiness.add(new Quote("If you want others to be happy, practice compassion. If you want to be happy, practice compassion.", "Dalai Lama"));
        happiness.add(new Quote("Happiness is not in the mere possession of money; it lies in the joy of achievement.", "Franklin D. Roosevelt"));
        happiness.add(new Quote("The only thing that will make you happy is being happy with who you are.", "Goldie Hawn"));
        happiness.add(new Quote("Happiness is a butterfly, which when pursued, is always just beyond your grasp.", "Nathaniel Hawthorne"));
        happiness.add(new Quote("There is only one happiness in this life, to love and be loved.", "George Sand"));
        happiness.add(new Quote("Happiness is not a destination, it is a way of life.", "Burton Hills"));
        happiness.add(new Quote("The secret of happiness is something to do.", "John Burroughs"));
        happiness.add(new Quote("Happiness resides not in possessions, and not in gold, happiness dwells in the soul.", "Democritus"));
        happiness.add(new Quote("If you are not happy here and now, you never will be.", "Taisen Deshimaru"));
        happiness.add(new Quote("Happiness is an inside job.", "William Arthur Ward"));
        happiness.add(new Quote("Most people are as happy as they make up their minds to be.", "Abraham Lincoln"));
        happiness.add(new Quote("Happiness is letting go of what you think your life is supposed to look like.", "Mandy Hale"));
        happiness.add(new Quote("The secret of happiness is to live moment by moment and to thank God for what He is sending us every day.", "Henri J.M. Nouwen"));
        happiness.add(new Quote("Happiness is not something you experience, it's something you remember.", "Oscar Levant"));
        happiness.add(new Quote("The key to being happy is knowing you have the power to choose what to accept and what to let go.", "Dodinsky"));
        happiness.add(new Quote("Happiness is a choice. You can choose to be happy.", "Valerie Bertinelli"));
        happiness.add(new Quote("Being happy doesn't mean that everything is perfect. It means that you've decided to look beyond the imperfections.", "Unknown"));
        happiness.add(new Quote("The happiest people don't have the best of everything, they just make the best of everything.", "Unknown"));
        happiness.add(new Quote("Happiness is a state of mind. It's just according to the way you look at things.", "Walt Disney"));
        happiness.add(new Quote("Happiness is the highest form of health.", "Dalai Lama"));
        happiness.add(new Quote("Happiness makes up in height for what it lacks in length.", "Robert Frost"));
        happiness.add(new Quote("The secret of happiness is variety, but the secret of variety, like the secret of all spices, is knowing when to use it.", "Daniel Gilbert"));
        happiness.add(new Quote("Happiness is the only thing that multiplies when you share it.", "Albert Schweitzer"));
        happiness.add(new Quote("Success is not the key to happiness. Happiness is the key to success.", "Albert Schweitzer"));
        happiness.add(new Quote("Happiness is not having what you want. It is appreciating what you have.", "Unknown"));
        happiness.add(new Quote("The art of being happy lies in the power of extracting happiness from common things.", "Henry Ward Beecher"));
        happiness.add(new Quote("Happiness consists in getting enough sleep. Just that, nothing more.", "Robert A. Heinlein"));
        happiness.add(new Quote("Happiness is found in doing, not merely possessing.", "Napoleon Hill"));
        happiness.add(new Quote("Happiness often sneaks in through a door you didn't know you left open.", "John Barrymore"));
        happiness.add(new Quote("The secret to happiness is low expectations.", "Barry Schwartz"));
        happiness.add(new Quote("Happiness is the spiritual experience of living every minute with love, grace, and gratitude.", "Denis Waitley"));

        // LEADERSHIP QUOTES (60+ quotes)
        List<Quote> leadership = new ArrayList<>();
        leadership.add(new Quote("A leader is one who knows the way, goes the way, and shows the way.", "John C. Maxwell"));
        leadership.add(new Quote("The greatest leader is not necessarily the one who does the greatest things.", "Ronald Reagan"));
        leadership.add(new Quote("Leadership is not about being in charge. It's about taking care of those in your charge.", "Simon Sinek"));
        leadership.add(new Quote("A good leader takes a little more than his share of the blame, a little less than his share of the credit.", "Arnold H. Glasow"));
        leadership.add(new Quote("Leadership is the capacity to translate vision into reality.", "Warren Bennis"));
        leadership.add(new Quote("The art of leadership is saying no, not saying yes.", "Tony Blair"));
        leadership.add(new Quote("Before you are a leader, success is all about growing yourself.", "Jack Welch"));
        leadership.add(new Quote("Leadership is not a position or a title, it is action and example.", "McGannon"));
        leadership.add(new Quote("A leader is best when people barely know he exists.", "Lao Tzu"));
        leadership.add(new Quote("The challenge of leadership is to be strong, but not rude.", "Jim Rohn"));
        leadership.add(new Quote("Leadership is about making others better as a result of your presence.", "Sheryl Sandberg"));
        leadership.add(new Quote("Great leaders are almost always great simplifiers.", "Colin Powell"));
        leadership.add(new Quote("Leadership is not about titles, positions, or flowcharts.", "John Maxwell"));
        leadership.add(new Quote("The first responsibility of a leader is to define reality.", "Max DePree"));
        leadership.add(new Quote("Leadership is the art of getting someone else to do something you want done.", "Dwight D. Eisenhower"));
        leadership.add(new Quote("A true leader has the confidence to stand alone.", "Douglas MacArthur"));
        leadership.add(new Quote("Leadership is about empathy. It is about having the ability to relate to and connect with people.", "Oprah Winfrey"));
        leadership.add(new Quote("The function of leadership is to produce more leaders, not more followers.", "Ralph Nader"));
        leadership.add(new Quote("Leadership is solving problems. The day soldiers stop bringing you their problems is the day you have stopped leading them.", "Colin Powell"));
        leadership.add(new Quote("Innovation distinguishes between a leader and a follower.", "Steve Jobs"));
        leadership.add(new Quote("A leader is a dealer in hope.", "Napoleon Bonaparte"));
        leadership.add(new Quote("Leadership is not about being popular. It is about being right and being strong.", "Amy Poehler"));
        leadership.add(new Quote("The key to successful leadership today is influence, not authority.", "Kenneth Blanchard"));
        leadership.add(new Quote("Leadership is about vision and responsibility, not power.", "Seth Berkley"));
        leadership.add(new Quote("Great leaders are willing to sacrifice their own personal interests for the good of the team.", "John Wooden"));
        leadership.add(new Quote("Leadership is the ability to guide others without force into a direction or decision that leaves them still feeling empowered.", "Lisa Cash Hanson"));
        leadership.add(new Quote("A leader takes people where they want to go. A great leader takes people where they don't necessarily want to go.", "Rosalynn Carter"));
        leadership.add(new Quote("Leadership is about creating a way for people to contribute to making something extraordinary happen.", "Alan Keith"));
        leadership.add(new Quote("The very essence of leadership is that you have to have vision.", "Theodore Hesburgh"));
        leadership.add(new Quote("Leadership is not about forcing your will on others. It's about mastering the art of letting go.", "Phil Jackson"));
        leadership.add(new Quote("A leader's job is not to do the work for others, it's to help others figure out how to do it themselves.", "Simon Sinek"));
        leadership.add(new Quote("Leadership is about taking responsibility, not making excuses.", "Mitt Romney"));
        leadership.add(new Quote("True leadership stems from individuality that is honestly and sometimes imperfectly expressed.", "Sheryl Sandberg"));
        leadership.add(new Quote("Leadership is the ability to facilitate movement in the needed direction and have people feel good about it.", "Tom Smith"));
        leadership.add(new Quote("The greatest gift of leadership is a boss who wants you to be successful.", "Jon Taffer"));
        leadership.add(new Quote("Leadership is about being authentic, being yourself.", "Indra Nooyi"));
        leadership.add(new Quote("A good leader inspires people to have confidence in the leader, a great leader inspires people to have confidence in themselves.", "Eleanor Roosevelt"));
        leadership.add(new Quote("Leadership is not about what you achieve, but what you make others achieve.", "Unknown"));
        leadership.add(new Quote("The price of greatness is responsibility.", "Winston Churchill"));
        leadership.add(new Quote("Leadership is about serving others, not being served.", "Ken Blanchard"));
        leadership.add(new Quote("A leader is someone who demonstrates what's possible.", "Mark Yarnell"));
        leadership.add(new Quote("Leadership is about making the right decision and then making the decision right.", "Unknown"));
        leadership.add(new Quote("Great leaders don't need to act tough. Their confidence and humility serve to underscore their toughness.", "Simon Sinek"));
        leadership.add(new Quote("Leadership is not wielding authority - it's empowering people.", "Becky Brodin"));
        leadership.add(new Quote("The final test of a leader is that he leaves behind him in other men the conviction and the will to carry on.", "Walter Lippmann"));
        leadership.add(new Quote("Leadership is about influence, nothing more, nothing less.", "John Maxwell"));
        leadership.add(new Quote("A leader is someone who knows what they don't know and is brave enough to admit it.", "Simon Sinek"));
        leadership.add(new Quote("Leadership is about character, integrity, and creating a vision that others can follow.", "John McCain"));
        leadership.add(new Quote("The best leaders are those who can lead themselves first.", "Unknown"));
        leadership.add(new Quote("Leadership is not about being perfect, it's about being authentic.", "Brené Brown"));
        leadership.add(new Quote("A true leader always keeps an element of surprise up his sleeve.", "Benjamin Disraeli"));
        leadership.add(new Quote("Leadership is about creating an environment where people can do their best work.", "Ken Blanchard"));
        leadership.add(new Quote("The best leaders are those the people hardly know exist.", "Lao Tzu"));
        leadership.add(new Quote("Leadership is about doing the right thing, even when no one is watching.", "C.S. Lewis"));
        leadership.add(new Quote("A leader's role is to raise people's aspirations for what they can become.", "David Gergen"));
        leadership.add(new Quote("Leadership is about turning vision into reality.", "Warren Bennis"));
        leadership.add(new Quote("The mark of a great leader is their ability to develop other leaders.", "John Maxwell"));
        leadership.add(new Quote("Leadership is about making people feel that they are part of something bigger than themselves.", "Oprah Winfrey"));
        leadership.add(new Quote("The best leaders are servants first.", "Robert Greenleaf"));
        leadership.add(new Quote("Leadership is about having the courage to make unpopular decisions.", "Harry Truman"));
        leadership.add(new Quote("A leader's legacy is measured by the success of those they've led.", "Unknown"));

        // DREAMS QUOTES (60+ quotes)
        List<Quote> dreams = new ArrayList<>();
        dreams.add(new Quote("The future belongs to those who believe in the beauty of their dreams.", "Eleanor Roosevelt"));
        dreams.add(new Quote("A year from now you may wish you had started today.", "Karen Lamb"));
        dreams.add(new Quote("You are never too old to set another goal or to dream a new dream.", "C.S. Lewis"));
        dreams.add(new Quote("All our dreams can come true if we have the courage to pursue them.", "Walt Disney"));
        dreams.add(new Quote("The biggest adventure you can take is to live the life of your dreams.", "Oprah Winfrey"));
        dreams.add(new Quote("Dream big and dare to fail.", "Norman Vaughan"));
        dreams.add(new Quote("If you can dream it, you can do it.", "Walt Disney"));
        dreams.add(new Quote("A dream doesn't become reality through magic; it takes sweat, determination and hard work.", "Colin Powell"));
        dreams.add(new Quote("Hold fast to dreams, for if dreams die, life is a broken-winged bird that cannot fly.", "Langston Hughes"));
        dreams.add(new Quote("Dreams are the touchstones of our characters.", "Henry David Thoreau"));
        dreams.add(new Quote("The only thing worse than being blind is having sight but no vision.", "Helen Keller"));
        dreams.add(new Quote("A dream you dream alone is only a dream. A dream you dream together is reality.", "Yoko Ono"));
        dreams.add(new Quote("Dreams don't work unless you do.", "John C. Maxwell"));
        dreams.add(new Quote("If your dreams don't scare you, they are too small.", "Richard Branson"));
        dreams.add(new Quote("The way to get started is to quit talking and begin doing.", "Walt Disney"));
        dreams.add(new Quote("Dreams are today's answers to tomorrow's questions.", "Edgar Cayce"));
        dreams.add(new Quote("A goal is a dream with a deadline.", "Napoleon Hill"));
        dreams.add(new Quote("Don't give up on your dreams, or your dreams will give up on you.", "John Wooden"));
        dreams.add(new Quote("Dreams are necessary to life.", "Anais Nin"));
        dreams.add(new Quote("The distance between your dreams and reality is called action.", "Unknown"));
        dreams.add(new Quote("Dreams are the seeds of change.", "Debby Boone"));
        dreams.add(new Quote("All men dream, but not equally.", "T.E. Lawrence"));
        dreams.add(new Quote("A single dream is more powerful than a thousand realities.", "J.R.R. Tolkien"));
        dreams.add(new Quote("Dreams are not what you see in your sleep, dreams are things which do not let you sleep.", "A.P.J. Abdul Kalam"));
        dreams.add(new Quote("The biggest dreams happen when you're outside of your comfort zone.", "Unknown"));
        dreams.add(new Quote("Your dreams are valid.", "Lupita Nyong'o"));
        dreams.add(new Quote("Dreams come true. Without that possibility, nature would not incite us to have them.", "John Updike"));
        dreams.add(new Quote("Don't let small minds convince you that your dreams are too big.", "Unknown"));
        dreams.add(new Quote("Dreams are illustrations from the book your soul is writing about you.", "Marsha Norman"));
        dreams.add(new Quote("A man is not old until regrets take the place of dreams.", "John Barrymore"));
        dreams.add(new Quote("The dreams of yesterday are the hopes of today and the reality of tomorrow.", "Robert H. Goddard"));
        dreams.add(new Quote("Dreams are renewable. No matter what our age or condition, there are still untapped possibilities within us.", "Dale Turner"));
        dreams.add(new Quote("Every great dream begins with a dreamer.", "Harriet Tubman"));
        dreams.add(new Quote("Dreams are the foundation stones of reality.", "Unknown"));
        dreams.add(new Quote("Follow your dreams, they know the way.", "Kobi Yamada"));
        dreams.add(new Quote("Dreams require down payments. Dreams are free, but the journey isn't.", "John Maxwell"));
        dreams.add(new Quote("The moment you give up your dreams is the moment you give up on yourself.", "Unknown"));
        dreams.add(new Quote("Dreams are like stars; you may never touch them, but if you follow them they will lead you to your destiny.", "Liam Payne"));
        dreams.add(new Quote("You have to dream before your dreams can come true.", "A.P.J. Abdul Kalam"));
        dreams.add(new Quote("Dreams are the architects of our future.", "Unknown"));
        dreams.add(new Quote("The only limits to our realization of tomorrow will be our doubts of today.", "Franklin D. Roosevelt"));
        dreams.add(new Quote("Dreams are whispers from the soul.", "Unknown"));
        dreams.add(new Quote("Chase your dreams until you catch them... and then dream, catch, and dream again!", "Dee Marie"));
        dreams.add(new Quote("A dream deferred is a dream denied.", "Langston Hughes"));
        dreams.add(new Quote("Dreams are messages from the deep.", "Frank Herbert"));
        dreams.add(new Quote("Never give up on a dream just because of the time it will take to accomplish it.", "Earl Nightingale"));
        dreams.add(new Quote("Dreams are the language of God.", "Paulo Coelho"));
        dreams.add(new Quote("The more you can dream, the more you can do.", "Michael Korda"));
        dreams.add(new Quote("Dreams are free. Goals have a cost.", "Unknown"));
        dreams.add(new Quote("I dream my painting and I paint my dream.", "Vincent Van Gogh"));
        dreams.add(new Quote("Dreams are like may never touch them, but if you follow them they will lead you to your destiny.", "Unknown"));
        dreams.add(new Quote("Dreams are powerful because they are the language of the heart.", "Unknown"));
        dreams.add(new Quote("All successful people men and women are big dreamers.", "Brian Tracy"));
        dreams.add(new Quote("Dreams are not just wishes, they are the blueprint to your reality.", "Unknown"));
        dreams.add(new Quote("The best dreams happen when you're awake.", "Cherie Gilderbloom"));
        dreams.add(new Quote("Dreams are the fuel that ignites the engine of possibility.", "Unknown"));
        dreams.add(new Quote("Your dreams don't have an expiration date.", "Unknown"));
        dreams.add(new Quote("Dreams are the preview of life's coming attractions.", "Albert Einstein"));
        dreams.add(new Quote("Every accomplishment starts with the decision to try and the dream to succeed.", "Unknown"));
        dreams.add(new Quote("Dreams are the windows to the soul.", "Unknown"));

        // WISDOM QUOTES (70+ quotes)
        List<Quote> wisdom = new ArrayList<>();
        wisdom.add(new Quote("It is during our darkest moments that we must focus to see the light.", "Aristotle"));
        wisdom.add(new Quote("The best time to plant a tree was 20 years ago. The second best time is now.", "Chinese Proverb"));
        wisdom.add(new Quote("Yesterday is history, tomorrow is a mystery, today is a gift.", "Eleanor Roosevelt"));
        wisdom.add(new Quote("The only true wisdom is in knowing you know nothing.", "Socrates"));
        wisdom.add(new Quote("In the middle of difficulty lies opportunity.", "Albert Einstein"));
        wisdom.add(new Quote("It does not matter how slowly you go as long as you do not stop.", "Confucius"));
        wisdom.add(new Quote("The journey of a thousand miles begins with one step.", "Lao Tzu"));
        wisdom.add(new Quote("What lies behind us and what lies before us are tiny matters compared to what lies within us.", "Ralph Waldo Emerson"));
        wisdom.add(new Quote("The only source of knowledge is experience.", "Albert Einstein"));
        wisdom.add(new Quote("Experience is the teacher of all things.", "Julius Caesar"));
        wisdom.add(new Quote("Wisdom is not a product of schooling but of the lifelong attempt to acquire it.", "Albert Einstein"));
        wisdom.add(new Quote("The fool doth think he is wise, but the wise man knows himself to be a fool.", "William Shakespeare"));
        wisdom.add(new Quote("Knowledge speaks, but wisdom listens.", "Jimi Hendrix"));
        wisdom.add(new Quote("The way I see it, if you want the rainbow, you gotta put up with the rain.", "Dolly Parton"));
        wisdom.add(new Quote("Knowing yourself is the beginning of all wisdom.", "Aristotle"));
        wisdom.add(new Quote("The only way to make sense out of change is to plunge into it, move with it, and join the dance.", "Alan Watts"));
        wisdom.add(new Quote("We are what we repeatedly do. Excellence, then, is not an act, but a habit.", "Aristotle"));
        wisdom.add(new Quote("The unexamined life is not worth living.", "Socrates"));
        wisdom.add(new Quote("Turn your wounds into wisdom.", "Oprah Winfrey"));
        wisdom.add(new Quote("Yesterday is gone. Tomorrow has not yet come. We have only today. Let us begin.", "Mother Teresa"));
        wisdom.add(new Quote("If you want to go fast, go alone. If you want to go far, go together.", "African Proverb"));
        wisdom.add(new Quote("The greatest enemy of knowledge is not ignorance, it is the illusion of knowledge.", "Stephen Hawking"));
        wisdom.add(new Quote("A wise man learns more from his enemies than a fool from his friends.", "Baltasar Gracián"));
        wisdom.add(new Quote("The important thing is not to stop questioning.", "Albert Einstein"));
        wisdom.add(new Quote("Life is really simple, but we insist on making it complicated.", "Confucius"));
        wisdom.add(new Quote("The mind is everything. What you think you become.", "Buddha"));
        wisdom.add(new Quote("Peace cannot be kept by force; it can only be achieved by understanding.", "Albert Einstein"));
        wisdom.add(new Quote("The wise find pleasure in water; the virtuous find pleasure in hills.", "Confucius"));
        wisdom.add(new Quote("Three things cannot be long hidden: the sun, the moon, and the truth.", "Buddha"));
        wisdom.add(new Quote("The best revenge is not to be like your enemy.", "Marcus Aurelius"));
        wisdom.add(new Quote("You have power over your mind - not outside events. Realize this, and you will find strength.", "Marcus Aurelius"));
        wisdom.add(new Quote("When the student is ready, the teacher will appear.", "Buddhist Proverb"));
        wisdom.add(new Quote("The cave you fear to enter holds the treasure you seek.", "Joseph Campbell"));
        wisdom.add(new Quote("Be yourself; everyone else is already taken.", "Oscar Wilde"));
        wisdom.add(new Quote("The two most important days in your life are the day you are born and the day you find out why.", "Mark Twain"));
        wisdom.add(new Quote("It is better to remain silent at the risk of being thought a fool, than to talk and remove all doubt.", "Mark Twain"));
        wisdom.add(new Quote("The truth will set you free, but first it will piss you off.", "Joe Klaas"));
        wisdom.add(new Quote("We cannot solve our problems with the same thinking we used when we created them.", "Albert Einstein"));
        wisdom.add(new Quote("The greatest glory in living lies not in never falling, but in rising every time we fall.", "Nelson Mandela"));
        wisdom.add(new Quote("In three words I can sum up everything I've learned about life: it goes on.", "Robert Frost"));
        wisdom.add(new Quote("Be who you are and say what you feel, because those who mind don't matter and those who matter don't mind.", "Bernard M. Baruch"));
        wisdom.add(new Quote("You miss 100% of the shots you don't take.", "Wayne Gretzky"));
        wisdom.add(new Quote("Whether you think you can or you think you can't, you're right.", "Henry Ford"));
        wisdom.add(new Quote("I have learned throughout my life as a composer chiefly through my mistakes and pursuits of false assumptions.", "Igor Stravinsky"));
        wisdom.add(new Quote("The only impossible journey is the one you never begin.", "Tony Robbins"));
        wisdom.add(new Quote("In this life we cannot do great things. We can only do small things with great love.", "Mother Teresa"));
        wisdom.add(new Quote("If you judge people, you have no time to love them.", "Mother Teresa"));
        wisdom.add(new Quote("Darkness cannot drive out darkness: only light can do that. Hate cannot drive out hate: only love can do that.", "Martin Luther King Jr."));
        wisdom.add(new Quote("The time is always right to do what is right.", "Martin Luther King Jr."));
        wisdom.add(new Quote("Injustice anywhere is a threat to justice everywhere.", "Martin Luther King Jr."));
        wisdom.add(new Quote("Life's most persistent and urgent question is, 'What are you doing for others?'", "Martin Luther King Jr."));
        wisdom.add(new Quote("The ultimate measure of a man is not where he stands in moments of comfort and convenience, but where he stands at times of challenge and controversy.", "Martin Luther King Jr."));
        wisdom.add(new Quote("We must learn to live together as brothers or perish together as fools.", "Martin Luther King Jr."));
        wisdom.add(new Quote("An eye for an eye only ends up making the whole world blind.", "Mahatma Gandhi"));
        wisdom.add(new Quote("Live as if you were to die tomorrow. Learn as if you were to live forever.", "Mahatma Gandhi"));
        wisdom.add(new Quote("The weak can never forgive. Forgiveness is the attribute of the strong.", "Mahatma Gandhi"));
        wisdom.add(new Quote("Happiness is when what you think, what you say, and what you do are in harmony.", "Mahatma Gandhi"));
        wisdom.add(new Quote("You must be the change you wish to see in the world.", "Mahatma Gandhi"));
        wisdom.add(new Quote("In a gentle way, you can shake the world.", "Mahatma Gandhi"));
        wisdom.add(new Quote("The best way to find yourself is to lose yourself in the service of others.", "Mahatma Gandhi"));
        wisdom.add(new Quote("Where there is love there is life.", "Mahatma Gandhi"));
        wisdom.add(new Quote("The future depends on what you do today.", "Mahatma Gandhi"));
        wisdom.add(new Quote("Strength does not come from physical capacity. It comes from an indomitable will.", "Mahatma Gandhi"));
        wisdom.add(new Quote("A man is but the product of his thoughts. What he thinks, he becomes.", "Mahatma Gandhi"));
        wisdom.add(new Quote("You yourself, as much as anybody in the entire universe, deserve your love and affection.", "Buddha"));
        wisdom.add(new Quote("Thousands of candles can be lighted from a single candle, and the life of the candle will not be shortened.", "Buddha"));
        wisdom.add(new Quote("Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment.", "Buddha"));
        wisdom.add(new Quote("Health is the greatest gift, contentment the greatest wealth, faithfulness the best relationship.", "Buddha"));
        wisdom.add(new Quote("If you truly loved yourself, you could never hurt another.", "Buddha"));
        wisdom.add(new Quote("Better than a thousand hollow words, is one word that brings peace.", "Buddha"));
        wisdom.add(new Quote("The mind is everything. What you think you become.", "Buddha"));
        wisdom.add(new Quote("Peace comes from within. Do not seek it without.", "Buddha"));

        // INSPIRATIONAL QUOTES (70+ quotes)
        List<Quote> inspirational = new ArrayList<>();
        inspirational.add(new Quote("Try to be a rainbow in someone's cloud.", "Maya Angelou"));
        inspirational.add(new Quote("In this life we cannot do great things. We can only do small things with great love.", "Mother Teresa"));
        inspirational.add(new Quote("Kindness is a language which the deaf can hear and the blind can see.", "Mark Twain"));
        inspirational.add(new Quote("No act of kindness, no matter how small, is ever wasted.", "Aesop"));
        inspirational.add(new Quote("The best and most beautiful things in the world cannot be seen or even touched.", "Helen Keller"));
        inspirational.add(new Quote("Spread love everywhere you go.", "Mother Teresa"));
        inspirational.add(new Quote("When you have a dream, you've got to grab it and never let go.", "Carol Burnett"));
        inspirational.add(new Quote("Nothing is impossible, the word itself says 'I'm possible'!", "Audrey Hepburn"));
        inspirational.add(new Quote("Keep your face always toward the sunshine—and shadows will fall behind you.", "Walt Whitman"));
        inspirational.add(new Quote("Whether you think you can or you think you can't, you're right.", "Henry Ford"));
        inspirational.add(new Quote("The only way to do great work is to love what you do.", "Steve Jobs"));
        inspirational.add(new Quote("Life is what happens when you're busy making other plans.", "John Lennon"));
        inspirational.add(new Quote("The future belongs to those who believe in the beauty of their dreams.", "Eleanor Roosevelt"));
        inspirational.add(new Quote("It is during our darkest moments that we must focus to see the light.", "Aristotle"));
        inspirational.add(new Quote("Whoever is happy will make others happy too.", "Anne Frank"));
        inspirational.add(new Quote("Do not go where the path may lead, go instead where there is no path and leave a trail.", "Ralph Waldo Emerson"));
        inspirational.add(new Quote("You will face many defeats in life, but never let yourself be defeated.", "Maya Angelou"));
        inspirational.add(new Quote("The greatest glory in living lies not in never falling, but in rising every time we fall.", "Nelson Mandela"));
        inspirational.add(new Quote("In the end, we will remember not the words of our enemies, but the silence of our friends.", "Martin Luther King Jr."));
        inspirational.add(new Quote("The purpose of our lives is to be happy.", "Dalai Lama"));
        inspirational.add(new Quote("Life is really simple, but we insist on making it complicated.", "Confucius"));
        inspirational.add(new Quote("May you live all the days of your life.", "Jonathan Swift"));
        inspirational.add(new Quote("Life is a succession of lessons which must be lived to be understood.", "Helen Keller"));
        inspirational.add(new Quote("You only live once, but if you do it right, once is enough.", "Mae West"));
        inspirational.add(new Quote("Many of life's failures are people who did not realize how close they were to success when they gave up.", "Thomas A. Edison"));
        inspirational.add(new Quote("The way to get started is to quit talking and begin doing.", "Walt Disney"));
        inspirational.add(new Quote("The pessimist sees difficulty in every opportunity. The optimist sees opportunity in every difficulty.", "Winston Churchill"));
        inspirational.add(new Quote("Don't let yesterday take up too much of today.", "Will Rogers"));
        inspirational.add(new Quote("You learn more from failure than from success. Don't let it stop you. Failure builds character.", "Unknown"));
        inspirational.add(new Quote("It's not whether you get knocked down, it's whether you get up.", "Vince Lombardi"));
        inspirational.add(new Quote("If you are working on something exciting that you really care about, you don't have to be pushed.", "Steve Jobs"));
        inspirational.add(new Quote("People who are crazy enough to think they can change the world, are the ones who do.", "Rob Siltanen"));
        inspirational.add(new Quote("Failure will never overtake me if my determination to succeed is strong enough.", "Og Mandino"));
        inspirational.add(new Quote("Entrepreneurs are great at dealing with uncertainty and also very good at minimizing risk.", "Mohnish Pabrai"));
        inspirational.add(new Quote("We may encounter many defeats but we must not be defeated.", "Maya Angelou"));
        inspirational.add(new Quote("Knowing is not enough; we must apply. Wishing is not enough; we must do.", "Johann Wolfgang von Goethe"));
        inspirational.add(new Quote("Imagine your life is perfect in every respect; what would it look like?", "Brian Tracy"));
        inspirational.add(new Quote("We can easily forgive a child who is afraid of the dark; the real tragedy of life is when men are afraid of the light.", "Plato"));
        inspirational.add(new Quote("Believe you can and you're halfway there.", "Theodore Roosevelt"));
        inspirational.add(new Quote("The only impossible journey is the one you never begin.", "Tony Robbins"));
        inspirational.add(new Quote("In this life we cannot do great things. We can only do small things with great love.", "Mother Teresa"));
        inspirational.add(new Quote("Only a life lived for others is a life worthwhile.", "Albert Einstein"));
        inspirational.add(new Quote("The purpose of our lives is to be happy.", "Dalai Lama"));
        inspirational.add(new Quote("You may say I'm a dreamer, but I'm not the only one.", "John Lennon"));
        inspirational.add(new Quote("So we beat on, boats against the current, borne back ceaselessly into the past.", "F. Scott Fitzgerald"));
        inspirational.add(new Quote("Be kind, for everyone you meet is fighting a hard battle.", "Plato"));
        inspirational.add(new Quote("Unable are the loved to die for love is immortality.", "Emily Dickinson"));
        inspirational.add(new Quote("Let us make our future now, and let us make our dreams tomorrow's reality.", "Malala Yousafzai"));
        inspirational.add(new Quote("All you need is love. But a little chocolate now and then doesn't hurt.", "Charles M. Schulz"));
        inspirational.add(new Quote("Listen to the mustn'ts, child. Listen to the don'ts. Listen to the shouldn'ts, the impossibles, the won'ts.", "Shel Silverstein"));
        inspirational.add(new Quote("A person who never made a mistake never tried anything new.", "Albert Einstein"));
        inspirational.add(new Quote("The person, be it gentleman or lady, who has not pleasure in a good novel, must be intolerably stupid.", "Jane Austen"));
        inspirational.add(new Quote("Imperfection is beauty, madness is genius and it's better to be absolutely ridiculous than absolutely boring.", "Marilyn Monroe"));
        inspirational.add(new Quote("Try to be like the turtle - at ease in your own shell.", "Bill Copeland"));
        inspirational.add(new Quote("Point me out the happy man and I will point you out either extreme egotism, selfishness, evil - or else an absolute ignorance.", "Graham Greene"));
        inspirational.add(new Quote("The opposite of love is not hate, it's indifference.", "Elie Wiesel"));
        inspirational.add(new Quote("It is not the strength of the body that counts, but the strength of the spirit.", "J.R.R. Tolkien"));
        inspirational.add(new Quote("There is nothing permanent except change.", "Heraclitus"));
        inspirational.add(new Quote("Twenty years from now you will be more disappointed by the things that you didn't do than by the ones you did do.", "Mark Twain"));
        inspirational.add(new Quote("It is never too late to be what you might have been.", "George Eliot"));
        inspirational.add(new Quote("A reader lives a thousand lives before he dies, said Jojen. The man who never reads lives only one.", "George R.R. Martin"));
        inspirational.add(new Quote("You can never get a cup of tea large enough or a book long enough to suit me.", "C.S. Lewis"));
        inspirational.add(new Quote("You have to write the book that wants to be written.", "Madeleine L'Engle"));
        inspirational.add(new Quote("Never trust anyone who has not brought a book with them.", "Lemony Snicket"));
        inspirational.add(new Quote("You can never understand one language until you understand at least two.", "Geoffrey Willans"));
        inspirational.add(new Quote("You can't stay in your corner of the Forest waiting for others to come to you.", "A.A. Milne"));
        inspirational.add(new Quote("Yesterday is history, tomorrow is a mystery, today is a gift of God, which is why we call it the present.", "Bill Keane"));
        inspirational.add(new Quote("I have not failed. I've just found 10,000 ways that won't work.", "Thomas A. Edison"));
        inspirational.add(new Quote("A woman is like a tea bag; you never know how strong it is until it's in hot water.", "Eleanor Roosevelt"));
        inspirational.add(new Quote("A day without sunshine is like, you know, night.", "Steve Martin"));
        inspirational.add(new Quote("This suspense is terrible. I hope it will last.", "Oscar Wilde"));
        inspirational.add(new Quote("When I was 5 years old, my mother always told me that happiness was the key to life.", "John Lennon"));
        inspirational.add(new Quote("We are all here on earth to help others; what on earth the others are here for I don't know.", "W. H. Auden"));
        inspirational.add(new Quote("Be who you are and say what you feel, because those who mind don't matter, and those who matter don't mind.", "Bernard M. Baruch"));

        // Add all categories to the map
        categorizedQuotes.put("Motivational", motivational);
        categorizedQuotes.put("Success", success);
        categorizedQuotes.put("Life", life);
        categorizedQuotes.put("Happiness", happiness);
        categorizedQuotes.put("Leadership", leadership);
        categorizedQuotes.put("Dreams", dreams);
        categorizedQuotes.put("Wisdom", wisdom);
        categorizedQuotes.put("Inspirational", inspirational);
    }

    public static Quote getRandomQuoteByCategory(String category) {
        List<Quote> quotes = categorizedQuotes.get(category);
        if (quotes != null && !quotes.isEmpty()) {
            int index = random.nextInt(quotes.size());
            return quotes.get(index);
        }
        return getRandomQuote(); // Fallback to random quote
    }

    public static Quote getRandomQuote() {
        List<Quote> allQuotes = new ArrayList<>();
        for (List<Quote> categoryQuotes : categorizedQuotes.values()) {
            allQuotes.addAll(categoryQuotes);
        }
        if (!allQuotes.isEmpty()) {
            int index = random.nextInt(allQuotes.size());
            return allQuotes.get(index);
        }
        return new Quote("Stay positive!", "InspireMe");
    }

    public static Quote getDailyQuote() {
        List<Quote> allQuotes = new ArrayList<>();
        for (List<Quote> categoryQuotes : categorizedQuotes.values()) {
            allQuotes.addAll(categoryQuotes);
        }
        if (!allQuotes.isEmpty()) {
            long daysSinceEpoch = System.currentTimeMillis() / (1000 * 60 * 60 * 24);
            int index = (int) (daysSinceEpoch % allQuotes.size());
            return allQuotes.get(index);
        }
        return new Quote("Have a great day!", "InspireMe");
    }

    // Get total count of quotes for debugging
    public static int getTotalQuoteCount() {
        int total = 0;
        for (List<Quote> categoryQuotes : categorizedQuotes.values()) {
            total += categoryQuotes.size();
        }
        return total;
    }

    // Get count by category
    public static int getCategoryQuoteCount(String category) {
        List<Quote> quotes = categorizedQuotes.get(category);
        return quotes != null ? quotes.size() : 0;
    }

    // Get all available categories
    public static String[] getAvailableCategories() {
        return categorizedQuotes.keySet().toArray(new String[0]);
    }
}